// import PDFDocument from "pdfkit";
// import Product from "../models/product.js";
// import moment from "moment";
// import path from "path";
// import { fileURLToPath } from "url";

// // For ES module __dirname workaround
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);

// export const generateStockReport = async (req, res) => {
//   try {
//     // Fetch products from MongoDB
//     const products = await Product.find().sort({ createdAt: -1 });

//     if (!products.length) {
//       return res.status(404).json({ message: "No products found to generate report", status: false });
//     }

//     // Create new PDF document
//     const doc = new PDFDocument({ margin: 40, size: "A4" });

//     // Set response headers to download PDF
//     res.setHeader("Content-Type", "application/pdf");
//     res.setHeader("Content-Disposition", "attachment; filename=HydraFoods_Stock_Report.pdf");

//     // Pipe directly to response
//     doc.pipe(res);

//     // Company info
//     const logoPath = path.join(__dirname, "../assets/hydrafoods_logo.png"); // place your logo in backend/assets
//     try {
//       doc.image(logoPath, 50, 30, { width: 70 });
//     } catch (err) {
//       console.log("Logo not found, skipping...");
//     }

//     // Header text
//     doc.fontSize(20).text("Hydra Foods", 130, 40);
//     doc.fontSize(14).text("Inventory Stock Report", 130, 70);
//     doc.moveDown(1);
//     doc.fontSize(10).text(`Generated on: ${moment().format("YYYY-MM-DD HH:mm:ss")}`);
//     doc.text(`Total Products: ${products.length}`);
//     doc.moveDown(2);

//     // Table Header
//     const headers = ["Item ID", "Product Name", "Qty", "Price", "Total Value", "Stock"];
//     const tableTop = 150;
//     const colPositions = [50, 130, 300, 360, 430, 510];

//     doc.font("Helvetica-Bold").fontSize(10);
//     headers.forEach((h, i) => doc.text(h, colPositions[i], tableTop));
//     doc.moveTo(50, tableTop + 12).lineTo(560, tableTop + 12).stroke();

//     // Table Rows
//     let y = tableTop + 25;
//     doc.font("Helvetica").fontSize(10);
//     products.forEach((p) => {
//       const total = p.price * p.quantity;
//       const isLowStock = p.quantity < 10;

//       if (isLowStock) {
//         doc.rect(45, y - 3, 515, 15).fill("#F4CCCC").stroke();
//         doc.fillColor("#000000");
//       }

//       doc.text(p.itemId, colPositions[0], y);
//       doc.text(p.name, colPositions[1], y, { width: 160 });
//       doc.text(p.quantity.toString(), colPositions[2], y);
//       doc.text(`Rs. ${p.price}`, colPositions[3], y);
//       doc.text(`Rs. ${total}`, colPositions[4], y);
//       doc.text(isLowStock ? "LOW" : "OK", colPositions[5], y);

//       y += 18;
//       if (y > 750) {
//         doc.addPage();
//         y = 100;
//       }
//     });

//     // Footer
//     doc.moveDown(2);
//     doc.fontSize(10).text("Generated by Hydra Foods Inventory Management System", { align: "center" });
//     doc.fontSize(8).text("© 2025 Hydra Foods. All Rights Reserved.", { align: "center" });

//     // Finalize PDF
//     doc.end();

//   } catch (error) {
//     res.status(500).json({ message: error.message || "Something went wrong while generating report", status: false });
//   }
// };


import PDFDocument from "pdfkit";
import Product from "../models/product.js";
import moment from "moment";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generateStockReport = async (req, res) => {
  try {
    const products = await Product.find().sort({ createdAt: -1 });

    if (!products.length) {
      return res.status(404).json({
        message: "No products found",
        status: false,
      });
    }

    // Create PDF document
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=HydraFoods_Stock_Report.pdf");
    doc.pipe(res);

    // ===== HEADER SECTION =====
    const logoPath = path.join(__dirname, "../assets/hydrafoods_logo.png");

    // Logo
    try {
      doc.image(logoPath, 50, 40, { width: 70 });
      console.log("logoPath", logoPath);
    } catch (error) {
      console.log("Logo not found, skipping image rendering...");
      console.log("logoPath", logoPath);
    }

    // Company Text (aligned properly next to logo)
    doc
      .font("Helvetica-Bold")
      .fontSize(20)
      .text("Hydra Foods", 130, 45)
      .moveDown(0.2);

    doc
      .font("Helvetica")
      .fontSize(13)
      .text("Inventory Stock Report", 130)
      .moveDown(0.2);

    doc
      .fontSize(10)
      .text(`Generated on: ${moment().format("YYYY-MM-DD HH:mm:ss")}`, 130)
      .text(`Total Products: ${products.length}`, 130);

    // Draw a horizontal separator line
    doc
      .moveTo(40, 120)
      .lineTo(560, 120)
      .strokeColor("#000000")
      .lineWidth(1)
      .stroke();

    // ===== TABLE HEADER =====
    const tableTop = 140;
    const colX = {
      itemId: 50,
      name: 130,
      quantity: 320,
      price: 390,
      total: 460,
      status: 530,
    };

    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .text("Item ID", colX.itemId, tableTop)
      .text("Product Name", colX.name, tableTop)
      .text("Qty", colX.quantity, tableTop, { width: 40, align: "center" })
      .text("Price (Rs)", colX.price, tableTop, { width: 60, align: "right" })
      .text("Total (Rs)", colX.total, tableTop, { width: 60, align: "right" })
      .text("Stock", colX.status, tableTop, { width: 40, align: "center" });

    doc
      .moveTo(40, tableTop + 12)
      .lineTo(560, tableTop + 12)
      .strokeColor("#000000")
      .stroke();

    // ===== TABLE BODY =====
    let y = tableTop + 25;
    const rowHeight = 20;
    let totalInventoryValue = 0;

    doc.font("Helvetica").fontSize(10);

    for (const p of products) {
      const totalValue = p.price * p.quantity;
      totalInventoryValue += totalValue;
      const lowStock = p.quantity < 10;

      // Add page break
      if (y > 750) {
        doc.addPage();
        y = 100;
      }

      // Highlight low stock
      if (lowStock) {
        doc.rect(45, y - 3, 515, 15).fill("#FDEDEC").stroke();
        doc.fillColor("#000000");
      }

      doc.text(p.itemId, colX.itemId, y);
      doc.text(p.name, colX.name, y, { width: 180 });
      doc.text(p.quantity.toString(), colX.quantity, y, { width: 40, align: "center" });
      doc.text(`Rs. ${p.price.toLocaleString()}`, colX.price, y, { width: 60, align: "right" });
      doc.text(`Rs. ${totalValue.toLocaleString()}`, colX.total, y, { width: 60, align: "right" });
      doc.text(lowStock ? "LOW" : "OK", colX.status, y, { width: 40, align: "center" });

      y += rowHeight;
    }

    // ===== SUMMARY =====
    y += 15;
    doc
      .moveTo(40, y)
      .lineTo(560, y)
      .strokeColor("#000000")
      .stroke();

    y += 10;
    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .text(`Total Inventory Value: Rs. ${totalInventoryValue.toLocaleString()}`, { align: "right" });

    // ===== FOOTER =====
    doc
      .font("Helvetica")
      .fontSize(10)
      .text("Generated by Hydra Foods Inventory Management System", 40, 780, {
        align: "center",
      })
      .fontSize(8)
      .text("© 2025 Hydra Foods. All Rights Reserved.", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    res.status(500).json({
      message: error.message || "Something went wrong while generating report",
      status: false,
    });
  }
};
